#!/bin/bash
# install-iwe-paths.sh — генерация $HOME/.iwe-paths + подключение через ~/.zshenv,
# ~/.bashrc (interactive/non-Claude-Code non-interactive shells) и
# .claude/settings.json env.BASH_ENV (Claude Code Bash tool — единственный
# механизм, который реально читает non-interactive bash-сессия, issue найден
# /audit-installation smoke-test 2026-07-23).
#
# Source-of-truth для IWE_* path-переменных (WP-219, DP.FM.009).
# Вызывается из:
#   - setup.sh (первичная установка)
#   - scripts/migrate-to-runtime-target.sh (миграция 0.28.x → 0.29.x)
#   - update.sh (повторная генерация после апгрейда — на случай если шаблон строки меняется)
#
# OwnerIntegrity: один файл — одно место. Раньше блок был дублирован в setup.sh [4d];
# при миграции ~/.iwe-paths не апгрейдился (Round 5 Евгения, 27 апр).
#
# Usage:
#   bash install-iwe-paths.sh --workspace PATH --governance REPO_NAME [--dry-run] [--quiet]
#
# Exit codes:
#   0 — успех
#   1 — некорректные аргументы

set -eu

WORKSPACE_DIR=""
GOVERNANCE_REPO=""
DRY_RUN=false
QUIET=false

while [ $# -gt 0 ]; do
    case "$1" in
        --workspace)  WORKSPACE_DIR="$2"; shift 2 ;;
        --governance) GOVERNANCE_REPO="$2"; shift 2 ;;
        --dry-run)    DRY_RUN=true; shift ;;
        --quiet|-q)   QUIET=true; shift ;;
        --help|-h)
            grep '^#' "$0" | head -20
            exit 0
            ;;
        *)
            echo "ERROR: Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

if [ -z "$WORKSPACE_DIR" ]; then
    echo "ERROR: --workspace обязателен" >&2
    exit 1
fi

WORKSPACE_DIR="${WORKSPACE_DIR/#\~/$HOME}"
GOVERNANCE_REPO="${GOVERNANCE_REPO:-DS-strategy}"

IWE_ENV_FILE="$WORKSPACE_DIR/.iwe-paths"
ZSHENV_FILE="$HOME/.zshenv"
BASHRC_FILE="$HOME/.bashrc"
IWE_ENV_MARKER="# IWE environment (WP-219, DP.FM.009): lookup-слой для путей к скриптам"

if $DRY_RUN; then
    $QUIET || echo "  [DRY RUN] Would write $IWE_ENV_FILE (workspace=$WORKSPACE_DIR, governance=$GOVERNANCE_REPO)"
    $QUIET || echo "  [DRY RUN] Would ensure $ZSHENV_FILE sources \$WORKSPACE_DIR/.iwe-paths"
    $QUIET || echo "  [DRY RUN] Would ensure $BASHRC_FILE sources \$WORKSPACE_DIR/.iwe-paths (prepended, before interactive-guard)"
    exit 0
fi

cat > "$IWE_ENV_FILE" <<IWEENV_EOF
# IWE environment variables
# Generated by install-iwe-paths.sh. Rerun setup.sh / migrate-to-runtime-target.sh / iwe-update to regenerate.
# Do not edit manually — changes will be lost.

export IWE_WORKSPACE="$WORKSPACE_DIR"
export IWE_TEMPLATE="\$IWE_WORKSPACE/FMT-exocortex-template"
export IWE_SCRIPTS="\$IWE_TEMPLATE/scripts"
export IWE_ROLES="\$IWE_TEMPLATE/roles"
export IWE_RUNTIME="\$IWE_WORKSPACE/.iwe-runtime"
export IWE_GOVERNANCE_REPO="$GOVERNANCE_REPO"
IWEENV_EOF

$QUIET || echo "  ✓ $IWE_ENV_FILE written (workspace=$WORKSPACE_DIR)"

# Ensure ~/.zshenv sources $WORKSPACE_DIR/.iwe-paths (idempotent)
if [ -f "$ZSHENV_FILE" ] && grep -qF "$IWE_ENV_MARKER" "$ZSHENV_FILE"; then
    $QUIET || echo "  ○ $ZSHENV_FILE already sources \$WORKSPACE_DIR/.iwe-paths"
else
    cat >> "$ZSHENV_FILE" <<ZSHENV_EOF

# IWE environment (WP-219, DP.FM.009): lookup-слой для путей к скриптам
_IWE_ROOT="$WORKSPACE_DIR"
[ -f "\$_IWE_ROOT/.iwe-paths" ] && source "\$_IWE_ROOT/.iwe-paths"
unset _IWE_ROOT
ZSHENV_EOF
    $QUIET || echo "  ✓ $ZSHENV_FILE → sources \$WORKSPACE_DIR/.iwe-paths"
fi

# Ensure ~/.bashrc sources $WORKSPACE_DIR/.iwe-paths — прописано ДО стандартного
# interactive-guard'а (`case $- in *i*) ;; *) return;; esac`), не после, как
# зафиксировано выше для .zshenv. Причина: неинтерактивные bash-сессии (Claude
# Code Bash tool и аналоги) вообще не доходят до строк после guard'а — тест
# 2026-07-23 (/audit-installation smoke-test) показал переменную unset даже
# при добавлении блока в конец файла; после переноса в начало — подхватывается.
# zsh не читает .bashrc вовсе, так что этот блок не мешает zsh-пользователям;
# добавляется безусловно, т.к. Claude Code Bash tool использует bash независимо
# от логин-шелла пользователя.
if [ -f "$BASHRC_FILE" ] && grep -qF "$IWE_ENV_MARKER" "$BASHRC_FILE"; then
    $QUIET || echo "  ○ $BASHRC_FILE already sources \$WORKSPACE_DIR/.iwe-paths"
else
    BASHRC_BLOCK="$IWE_ENV_MARKER
# Прописано ДО interactive-guard намеренно (см. install-iwe-paths.sh) —
# неинтерактивные bash-сессии не доходят дальше guard'а ниже.
_IWE_ROOT=\"$WORKSPACE_DIR\"
[ -f \"\$_IWE_ROOT/.iwe-paths\" ] && . \"\$_IWE_ROOT/.iwe-paths\"
unset _IWE_ROOT
"
    if [ -f "$BASHRC_FILE" ]; then
        BASHRC_PERM=$(stat -c %a "$BASHRC_FILE" 2>/dev/null || stat -f %Lp "$BASHRC_FILE" 2>/dev/null || echo 644)
        TMP_BASHRC=$(mktemp)
        printf '%s\n\n' "$BASHRC_BLOCK" > "$TMP_BASHRC"
        cat "$BASHRC_FILE" >> "$TMP_BASHRC"
        mv "$TMP_BASHRC" "$BASHRC_FILE"
        chmod "$BASHRC_PERM" "$BASHRC_FILE"
    else
        printf '%s\n' "$BASHRC_BLOCK" > "$BASHRC_FILE"
    fi
    $QUIET || echo "  ✓ $BASHRC_FILE → sources \$WORKSPACE_DIR/.iwe-paths (prepended, before interactive-guard)"
fi

# Ensure $WORKSPACE_DIR/.claude/settings.json sets env.BASH_ENV — the actual
# mechanism Claude Code's own Bash tool honors. Confirmed empirically
# (2026-07-23): the Bash tool's shell is non-interactive (`$-` has no `i`),
# so it never reads ~/.bashrc/~/.zshenv/--rcfile at all (bash only reads
# those for interactive shells) — the .bashrc block above helps every OTHER
# non-interactive caller (cron, CI, ssh host cmd), but not this one. BASH_ENV
# is the one bash variable non-interactive shells DO honor. settings.json is
# copied from the template earlier in setup.sh (step before [4d]), so it
# already exists here on a fresh install.
SETTINGS_FILE="$WORKSPACE_DIR/.claude/settings.json"
if ! command -v jq >/dev/null 2>&1; then
    $QUIET || echo "  ○ jq not found — skipping env.BASH_ENV in settings.json (add manually: {\"env\":{\"BASH_ENV\":\"$IWE_ENV_FILE\"}})"
elif [ ! -f "$SETTINGS_FILE" ]; then
    $QUIET || echo "  ○ $SETTINGS_FILE not found — skipping env.BASH_ENV"
elif [ "$(jq -r '.env.BASH_ENV // empty' "$SETTINGS_FILE" 2>/dev/null)" = "$IWE_ENV_FILE" ]; then
    $QUIET || echo "  ○ $SETTINGS_FILE already has env.BASH_ENV=$IWE_ENV_FILE"
else
    TMP_SETTINGS=$(mktemp)
    if jq --arg v "$IWE_ENV_FILE" '.env = ((.env // {}) + {BASH_ENV: $v})' "$SETTINGS_FILE" > "$TMP_SETTINGS" 2>/dev/null; then
        mv "$TMP_SETTINGS" "$SETTINGS_FILE"
        $QUIET || echo "  ✓ $SETTINGS_FILE → env.BASH_ENV=$IWE_ENV_FILE"
    else
        rm -f "$TMP_SETTINGS"
        $QUIET || echo "  ⚠ $SETTINGS_FILE — jq merge failed (malformed JSON?), env.BASH_ENV not set"
    fi
fi

# Auto-enable pre-commit hooks for IWE repos that have .githooks/
# (Claude peer-review, 2026-05-26 — BFS3)
for repo_dir in "$WORKSPACE_DIR"/* "$WORKSPACE_DIR"/*/*; do
    [ -d "$repo_dir/.git" ] || continue
    [ -d "$repo_dir/.githooks" ] || continue
    if [ "$(git -C "$repo_dir" config --local core.hooksPath 2>/dev/null)" != ".githooks" ]; then
        git -C "$repo_dir" config --local core.hooksPath .githooks
        $QUIET || echo "  ✓ $repo_dir → core.hooksPath=.githooks"
    fi
done
